name: Build Mod

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Compile Library
      run: dotnet build Mod.csproj --configuration Release --output ./build

    - name: Upload Finished DLL
      uses: actions/upload-artifact@v4
      with:
        name: AnimalCompanyMod
        path: ./build/*.dll
